version: '3.8'
services:
  node0:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PTH_DIR: node0
    container_name: node0
    ports:
    - 7050:7050
    - 6050:6050
    environment:
    - INITIAL_STAGE=0
    - BOOTSTRAP_NODES=172.28.0.2:7050,172.28.0.3:7050,172.28.0.4:7050
    - NODE_NAME=node0
    volumes:
    - ./model_parts:/inferd/model_parts
    networks:
      infernet:
        ipv4_address: 172.28.0.2
    working_dir: /inferd
    command:
    - run_node.py
  node1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PTH_DIR: node1
    container_name: node1
    ports:
    - 7051:7050
    - 6051:6050
    environment:
    - INITIAL_STAGE=1
    - BOOTSTRAP_NODES=172.28.0.2:7050,172.28.0.3:7050,172.28.0.4:7050
    - NODE_NAME=node1
    volumes:
    - ./model_parts:/inferd/model_parts
    networks:
      infernet:
        ipv4_address: 172.28.0.3
    working_dir: /inferd
    command:
    - run_node.py
  node2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PTH_DIR: node2
    container_name: node2
    ports:
    - 7052:7050
    - 6052:6050
    environment:
    - INITIAL_STAGE=2
    - BOOTSTRAP_NODES=172.28.0.2:7050,172.28.0.3:7050,172.28.0.4:7050
    - NODE_NAME=node2
    volumes:
    - ./model_parts:/inferd/model_parts
    networks:
      infernet:
        ipv4_address: 172.28.0.4
    working_dir: /inferd
    command:
    - run_node.py
networks:
  infernet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/16
