services:
  node0:
    build: .
    container_name: node0
    ports:
      - "7050:7050"
      - "6050:6050"
    environment:
      - INITIAL_STAGE=0
      - BOOTSTRAP_NODES=172.28.0.2:7050,172.28.0.3:7050,172.28.0.4:7050
    networks:
      infernet:
        ipv4_address: 172.28.0.2

  node1:
    build: .
    container_name: node1
    ports:
      - "7051:7050"
      - "6051:6050"
    environment:
      - INITIAL_STAGE=1
      - BOOTSTRAP_NODES=172.28.0.2:7050,172.28.0.3:7050,172.28.0.4:7050
    networks:
      infernet:
        ipv4_address: 172.28.0.3

  node2:
    build: .
    container_name: node2
    ports:
      - "7052:7050"
      - "6052:6050"
    environment:
      - INITIAL_STAGE=2
      - BOOTSTRAP_NODES=172.28.0.2:7050,172.28.0.3:7050,172.28.0.4:7050
    networks:
      infernet:
        ipv4_address: 172.28.0.4

networks:
  infernet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
